import type { Metadata } from "next";
import { ThemeProvider } from "../components/theme-provider";
import { Navbar }  from "../components/layout/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode })  {
  return (
    <html
      lang="en"
      className="h-dvh"
      suppressHydrationWarning
    >
      <ThemeProvider>
        <Navbar />
        <body className="bg-white text-neutral-900 dark:bg-neutral-950 dark:text-neutral-100">
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
